spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.110:3306/test?characterEncoding=utf-8&rewriteBatchedStatements=true
    hikari:
      jdbc-url: jdbc:mysql://192.168.1.110:3306/test?characterEncoding=utf-8&rewriteBatchedStatements=true
      username: root
      password: 123456
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
