spring:
  profiles:
#    active: h2
    active: mysql
  datasource:
    schema: classpath:sql/schema.sql
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
    mappings:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    git:
      mode: full